// @ts-nocheck
export const CFG = Object.freeze({
    world: {
        size: 10000,
        groundScale: 135,
        hillAmp: 32,
        cloudCount: 96,
        seaLevel: -84,
        wrapMargin: 160,
    },
    camera: {
        back: 18,
        front: 12,
        up: 6,
        rearUp: 3,
        fov: 70,
        zoomFov: 42,
        lookAhead: 18,
        lerp: 0.08,
        shake: 0.18,
    },
    player: {
        maxThrust: 52,
        boostThrust: 82,
        wepMax: 100,
        wepDrain: 22,
        wepRecharge: 14,
        hpRegen: 2.8,
        ammoReloadPerSecond: 18,
        turnRate: 1.4,
        rollRate: 3.2,
        pitchRate: 2.0,
        maxG: 6.5,
        maxSpeed: 140,
        minSpeed: 18,
        ammo: 420,
        hp: 120,
    },
    physics: {
        gravity: 0,
        drag: 0,
        lift: 0,
        stallSpeed: 0,
        wingArea: 18,
    },
    guns: {
        rof: 0.06,
        bulletSpeed: 210,
        spread: 0.004,
        damage: 18,
        muzzleOffset: 6.4,
        aimDistance: 1400,
        aimLift: 0,
        ttl: 2.4,
    },
    rockets: {
        count: 6,
        cooldown: 0.28,
        reloadInterval: 5.5,
        speed: 230,
        damage: 170,
        radius: 26,
        ttl: 5.5,
        muzzleOffset: 2.8,
    },
    bombs: {
        count: 4,
        cooldown: 0.45,
        reloadInterval: 8,
        gravity: 55,
        damage: 240,
        radius: 34,
        ttl: 8,
        dropOffset: 1.2,
    },
    ai: {
        wingmen: 2,
        enemies: 6,
        thinkRate: 0.2,
        fireDist: 420,
        seekDist: 1200,
        breakDist: 120,
        aimCos: 0.985,
    },
    team: {
        wingmanHp: 80,
        enemyHp: 70,
        respawnDelay: 4,
    },
});
